name: pr

on: [pull_request]

jobs:
  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@22455dee9e3a2ddc3d135315a7808c4754a6d312 # 2.0.16
    with:
      image-name: ts3exporter
      create-artifacts: false
