name: pr

on: [pull_request]

jobs:
  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@c60129fdec11c0ced690c6f35fb37dcb488e63f4 # 2.0.44
    with:
      image-name: ts3exporter
      create-artifacts: false
