name: pr

on: [pull_request]

jobs:
  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@f78634d1cc51dd41e41a0901e75ded32775e6fc7 # 2.0.29
    with:
      image-name: ts3exporter
      create-artifacts: false
