name: conventional-commits

on: [push]

jobs:
  conventional-compliance:
    uses: wittdennis/pipelines/.github/workflows/cog-validate.yaml@0d6d7ea86ee5a77cd1493ef7cae0a749787ce637 # 2.0.41
    with:
      check-latest-tag-only: true
