name: conventional-commits

on: [push]

jobs:
  conventional-compliance:
    uses: wittdennis/pipelines/.github/workflows/cog-validate.yaml@debf39105aa63e76e9e5f8527f6909292a6399d3 # 2.0.35
    with:
      check-latest-tag-only: true
