name: conventional-commits

on: [push]

jobs:
  conventional-compliance:
    uses: wittdennis/pipelines/.github/workflows/cog-validate.yaml@b65917377ef7ceeeb30ee3ec2a42135d403ca822 # 2.0.59
    with:
      check-latest-tag-only: true
