name: go-lint

on: [pull_request]

jobs:
  lint:
    uses: wittdennis/pipelines/.github/workflows/go-lint.yaml@956a18b30b1d66ffcfacf93b3fafcaacaf6f4eda # 2.0.54
    with:
      go-version: "1.27.1" # renovate: datasource=github-tags depName=golang/go extractVersion=^go(?<version>.*)$ versioning=semver
