name: go-lint

on: [pull_request]

jobs:
  lint:
    uses: wittdennis/pipelines/.github/workflows/go-lint.yaml@fb06128e939b3c347883b4a369d4bba39011ce0b # 2.0.60
    with:
      go-version: "1.27.1" # renovate: datasource=github-tags depName=golang/go extractVersion=^go(?<version>.*)$ versioning=semver
