name: publish-image

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/container-image-publish.yaml@a575c9b6835f8dbfd7127f93c1c1e4d588eb7d7d # 2.0.48
    permissions:
      packages: write
      contents: read
    with:
      image-name: ts3exporter
      registries: |
        docker.io
        ghcr.io
      registry-namespaces: |
        denniswitt
        wittdennis
    secrets:
      registry-passwords: |
        ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        ${{ secrets.GITHUB_TOKEN }}
