name: publish-image

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/container-image-publish.yaml@80d93272d8b0ad2988de6a14b6dca783ef97bb41 # 2.0.6
    permissions:
      packages: write
      contents: read
    with:
      image-name: ts3exporter
      registries: |
        docker.io
        ghcr.io
      registry-namespaces: |
        denniswitt
        wittdennis
    secrets:
      registry-passwords: |
        ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        ${{ secrets.GITHUB_TOKEN }}
