name: publish-image

on:
  release:
    types: published

jobs:
  publish:
    uses: wittdennis/.github/.github/workflows/publish-docker-image.yaml@master
    with:
      image-name: ts3exporter
    secrets:
      registry-password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
