name: publish-image

on:
  workflow_dispatch:
  release:
    types: published

jobs:
  publish:
    uses: wittdennis/pipelines/.github/workflows/container-image-publish.yaml@f2de7e15d3b6913b063c69a739c7ca3dca8249f2 # 2.0.36
    permissions:
      packages: write
      contents: read
    with:
      image-name: ts3exporter
      registries: |
        docker.io
        ghcr.io
      registry-namespaces: |
        denniswitt
        wittdennis
    secrets:
      registry-passwords: |
        ${{ secrets.DOCKER_REGISTRY_TOKEN }}
        ${{ secrets.GITHUB_TOKEN }}
