name: github-release

on:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: install cocogitto
        uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
        with:
          install-only: true

      - name: determine next version
        id: release
        run: |
          VERSION=$(cog bump --auto --dry-run)
          echo "version=$VERSION" >>"$GITHUB_OUTPUT"

  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@d7142ea4fc5237aae7ec616148530adc3577ec7d # 2.0.23
    with:
      check-latest-tag-only: true
      release-files: |
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_checksums.txt
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_darwin_amd64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_darwin_arm64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_386.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_amd64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_arm64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_windows_386.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_windows_amd64.tar.gz
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
    needs: get-version
