name: github-release

on:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: install cocogitto
        uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
        with:
          install-only: true

      - name: determine next version
        id: release
        run: |
          VERSION=$(cog bump --auto --dry-run)
          echo "version=$VERSION" >>"$GITHUB_OUTPUT"

  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@d1dffd228d24d880ae13b2b4c45d322f28848fea # 2.0.31
    with:
      check-latest-tag-only: true
      release-files: |
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_checksums.txt
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_darwin_amd64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_darwin_arm64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_386.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_amd64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_arm64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_windows_386.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_windows_amd64.tar.gz
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
    needs: get-version
