name: github-release

on:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: install cocogitto
        uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
        with:
          install-only: true

      - name: determine next version
        id: release
        run: |
          VERSION=$(cog bump --auto --dry-run)
          echo "version=$VERSION" >>"$GITHUB_OUTPUT"

  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@080601f5ad49ceb87c985716d349438d26c4b87b # 2.0.13
    with:
      check-latest-tag-only: true
      release-files: |
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_checksums.txt
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_darwin_amd64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_darwin_arm64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_386.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_amd64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_linux_arm64.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_windows_386.tar.gz
        dist/ts3exporter_${{ needs.get-version.outputs.version }}_windows_amd64.tar.gz
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
    needs: get-version
